language: scala
jdk: oraclejdk7
sudo: false
before_install: umask 0022
cache:
  directories:
   - $HOME/.scalding.dep.cache
script:
  - scripts/testValidator.sh
addons:
  apt:
    packages:
    - md5deep
    -
matrix:
  include:
#BASE TESTS
    - scala: 2.10.5
      env: BUILD="base" TEST_TARGET="scalding-args scalding-date maple" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.11.7
      env: BUILD="base" TEST_TARGET="scalding-args scalding-date maple" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.10.5
      env: BUILD="base" TEST_TARGET="scalding-avro scalding-hraven scalding-commons scalding-parquet scalding-parquet-scrooge"
      script: travis_wait "scripts/run_test.sh"

    - scala: 2.11.7
      env: BUILD="base" TEST_TARGET="scalding-avro scalding-hraven scalding-commons scalding-parquet scalding-parquet-scrooge" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.10.5
      env: BUILD="base" TEST_TARGET="scalding-core scalding-jdbc scalding-json scalding-db" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.11.7
      env: BUILD="base" TEST_TARGET="scalding-core scalding-jdbc scalding-json scalding-db" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.10.5
      env: BUILD="base" TEST_TARGET="scalding-hadoop-test" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.11.7
      env: BUILD="base" TEST_TARGET="scalding-hadoop-test" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.10.5
      env: BUILD="base" TEST_TARGET="scalding-serialization" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.11.7
      env: BUILD="base" TEST_TARGET="scalding-serialization" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.10.5
      env: BUILD="base" TEST_TARGET="scalding-thrift-macros" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.11.7
      env: BUILD="base" TEST_TARGET="scalding-thrift-macros" TRAVIS_WAIT=travis_wait
      script: "scripts/run_test.sh"

    - scala: 2.10.5
      env: BUILD="test tutorials and matrix tutorials and repl" TEST_TARGET="scalding-repl" TRAVIS_WAIT=travis_wait
      script:
      - "scripts/run_test.sh"
      - "scripts/build_assembly_no_test.sh scalding-assembly"
      - "scripts/test_tutorials.sh"
      - "scripts/build_assembly_no_test.sh scalding-assembly"
      - "scripts/test_matrix_tutorials.sh"

    - scala: 2.11.7
      env: BUILD="test tutorials and matrix tutorials and repl" TEST_TARGET="scalding-repl" TRAVIS_WAIT=travis_wait
      script:
      - "scripts/run_test.sh"
      - "scripts/build_assembly_no_test.sh scalding-assembly"
      - "scripts/test_tutorials.sh"
      - "scripts/build_assembly_no_test.sh scalding-assembly"
      - "scripts/test_matrix_tutorials.sh"

    - scala: 2.10.5
      env: BUILD="test repl and typed tutorials" TRAVIS_WAIT=travis_wait
      script:
      - "scripts/build_assembly_no_test.sh scalding-repl"
      - "scripts/test_repl_tutorial.sh"
      - "scripts/build_assembly_no_test.sh scalding-core"
      - "scripts/test_typed_tutorials.sh"
      - "scripts/build_assembly_no_test.sh execution-tutorial"
      - "scripts/test_execution_tutorial.sh"

    - scala: 2.11.7
      env: BUILD="test repl and typed tutorials" TRAVIS_WAIT=travis_wait
      script:
      - "scripts/build_assembly_no_test.sh scalding-repl"
      - "scripts/test_repl_tutorial.sh"
      - "scripts/build_assembly_no_test.sh scalding-core"
      - "scripts/test_typed_tutorials.sh"
      - "scripts/build_assembly_no_test.sh execution-tutorial"
      - "scripts/test_execution_tutorial.sh"
